### ISSUE TITLE
Hashing large inputs

### ISSUE THREAD

**Issue by bedax** [sbp/xoocycle#1]
Hello! First off, thank you very much for this excellent implementation. With normal hash functions, you can of course do something like

```
hasher = hasher_new()
hasher_add(&hasher, "hello ")
hasher_add(&hasher, "world")
hasher_finish(&hasher, out)
```

Which normally would give the same output as:

```
hasher = hasher_new()
hasher_add(&hasher, "hello world")
hasher_finish(&hasher, out)
```

But this doesn't seem to work with xoocycle, as a hash produced by xoocycle using the first method is different from the second.

Is this to be expected from all xoodyak implementations, or is it xoocycle-specific? I saw a `absorb_more` function in [Rust's implementation](https://docs.rs/xoodyak/0.7.0/xoodyak/trait.XoodyakCommon.html#method.absorb_more), but that doesn't seem to do it either, unless I'm missing something.

**Comment by bedax** [comment]
Having looked more at the Xoodyak paper, this behaviour seems to be a product of its design in general, so I'll close this now.

Thanks again!

**Comment by gvanas** [comment]
I think this is a legitimate suggestion. Xoodyak specifies a macroscopic API, like absorbing a string, but the implementation could allow to give this string in pieces.

This said, I see that we don't support this in the [XKCP](https://github.com/XKCP/XKCP) either, but I think we should, so we will try to update the XKCP's Xoodyak implementation in the future.

**Comment by xeyownt** [comment]
For more clarification (hopefully), Xoodyak indeed accepts at API level to absorb several strings before squeezing, but they'ill indeed be processed as independent strings. For instance, this could be used to absorb the content of several files stored in a tar.gz, and produce a hash over the collection of files, which would be different from eg. a hash on the concatenation of those files. Note that the same applies for `squeeze`.

As Gilles said though, Xoodyak expects the complete strings to be given at API level. Processing it in pieces is something that must be done in some implementation layer. It is strange though that the Rust function `absorb_more` mentioned above doesn't do exactly that because there is no such interface at API level.
